# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.20
        
    - name: Dependancies
      run:
        go get -u ./...

    - name: Build
      run: 
        go build -v ./...

    - name: Test
      run: 
        go test -v ./...
    
    
